datasource:
  modulo-size: 8
  center:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/hor-shard-center?autoReconnect=true&rewriteBatchedStatements=true&useSSL=true
    username: root
    password: root
    pool-name: center-pool
    maximum-pool-size: 200
    minimum-idle: 1
  ds:
    ds1:
      modulo: 0-3,5
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hor-shard-ds1?autoReconnect=true&rewriteBatchedStatements=true&useSSL=true
      username: root
      password: root
      pool-name: ds1-pool
      maximum-pool-size: 200
      minimum-idle: 1
    ds2:
      modulo: 4,6-7
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hor-shard-ds2?autoReconnect=true&rewriteBatchedStatements=true&useSSL=true
      username: root
      password: root
      pool-name: ds2-pool
      maximum-pool-size: 200
      minimum-idle: 1
